### ISSUE TITLE
Error in run.py

### ISSUE THREAD

**Issue by st186** [cyanamous/Self-Driving-Car-#1]
VIDEOIO ERROR: V4L: can't open camera by index 0
Traceback (most recent call last):
  File "run.py", line 19, in <module>
    image = scipy.misc.imresize(frame, [66, 200]) / 255.0
  File "/usr/local/lib/python3.5/dist-packages/numpy/lib/utils.py", line 101, in newfunc
    return func(*args, **kwds)
  File "/usr/local/lib/python3.5/dist-packages/scipy/misc/pilutil.py", line 555, in imresize
    im = toimage(arr, mode=mode)
  File "/usr/local/lib/python3.5/dist-packages/numpy/lib/utils.py", line 101, in newfunc
    return func(*args, **kwds)
  File "/usr/local/lib/python3.5/dist-packages/scipy/misc/pilutil.py", line 327, in toimage
    raise ValueError("'arr' does not have a suitable array shape for "
ValueError: 'arr' does not have a suitable array shape for any mode.

**Comment by 1660211616** [comment]
Can you solve this mistake?

**Comment by st186** [comment]
no

**Comment by tristanssun** [comment]
It's because you don't have a webcam plugged in.
